name: Build and Publish Python Package

on:
  release:
    types: [published]
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Determine version type
      id: version_type
      run: |
        if [ "${{ github.event_name }}" == "release" ]; then
          echo "RELEASE_VERSION=true" >> $GITHUB_ENV
        fi

    - name: Build package
      run: python -m build

    - name: Publish package
      if: always() && (
          github.event_name == 'release' ||
          github.ref == 'refs/heads/main'
        )
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}